version: "3"
services:
  spark-master:
    image: cluster-apache-spark:3.5.0
    container_name: master
    ports:
      - "9090:8080"
      - "7077:7077"
    volumes:
       - ./apps:/opt/spark-apps
       - ./data:/opt/spark-data
    environment:
      - SPARK_LOCAL_IP=spark-master
      - SPARK_WORKLOAD=master
    networks:
      iceberg:





  spark-worker-a:
    image: cluster-apache-spark:3.5.0
    container_name: worker
    ports:
      - "9091:8080"
      - "7000:7000"
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_CORES=30
      - SPARK_WORKER_MEMORY=10G
      - SPARK_DRIVER_MEMORY=10G
      - SPARK_EXECUTOR_MEMORY=10G
      - SPARK_WORKLOAD=worker
      - SPARK_LOCAL_IP=spark-worker-a
    volumes:
       - ./apps:/opt/spark-apps
       - ./data:/opt/spark-data
  
    networks:
      iceberg:

networks:
  iceberg: